<a href="https://colab.research.google.com/github/ashwin2805/summer-training/blob/main/day4/Copy_of_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('/Dropout_Academic Success - Sheet1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
dataset.head()

Marital status  Application mode  Application order  Course  \
0               1                17                  5     171   
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   

   Daytime/evening attendance  Previous qualification  \
0                           1                       1   
1                           1                       1   
2                           1                       1   
3                           1                       1   
4                           0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19   
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)  \
0                                    0   
1                                    6   
2                                    6   
3                                    6   
4                                    6   

   Curricular units 2nd sem (evaluations)  \
0                                       0   
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000   
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8   
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  
3            -0.8 -3.12  Graduate  
4            -0.3  0.79  Graduate  

[5 rows x 37 columns]

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[ 1.   17.    4.   ... 10.8   1.4   1.74]
 [ 4.   39.    1.   ... 13.9  -0.3   0.79]
 [ 1.   18.    1.   ...  9.4  -0.8  -3.12]
 ...
 [ 1.    1.    3.   ... 12.4   0.5   1.79]
 [ 1.    1.    1.   ... 15.5   2.8  -4.06]
 [ 1.    1.    1.   ... 12.7   3.7  -1.7 ]]


In [ ]:
print(y_train)

['Dropout' 'Graduate' 'Enrolled' ... 'Graduate' 'Dropout' 'Enrolled']


In [ ]:
print(X_test)

[[ 1.    1.    1.   ...  9.4  -0.8  -3.12]
 [ 1.    1.    1.   ... 10.8   1.4   1.74]
 [ 1.    1.    1.   ... 10.8   1.4   1.74]
 ...
 [ 4.   39.    1.   ... 15.5   2.8  -4.06]
 [ 1.    1.    1.   ... 16.2   0.3  -0.92]
 [ 1.   17.    4.   ... 13.9  -0.3   0.79]]


In [ ]:
print(y_test)

['Graduate' 'Dropout' 'Graduate' ... 'Enrolled' 'Graduate' 'Graduate']


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.29752208 -0.08824613  1.74301844 ... -0.29337163  0.11812785
   0.76262697]
 [ 4.77359915  1.16693991 -0.55865383 ...  0.87274574 -1.11077654
   0.34447277]
 [-0.29752208 -0.03119222 -0.55865383 ... -0.82000529 -1.472219
  -1.37656186]
 ...
 [-0.29752208 -1.00110871  0.97579435 ...  0.3084954  -0.53246859
   0.78463508]
 [-0.29752208 -1.00110871 -0.55865383 ...  1.47461278  1.13016676
  -1.79031443]
 [-0.29752208 -1.00110871 -0.55865383 ...  0.42134547  1.7807632
  -0.75153138]]


In [ ]:
print(X_test)

[[-0.29752208 -1.00110871 -0.55865383 ... -0.82000529 -1.472219
  -1.37656186]
 [-0.29752208 -1.00110871 -0.55865383 ... -0.29337163  0.11812785
   0.76262697]
 [-0.29752208 -1.00110871 -0.55865383 ... -0.29337163  0.11812785
   0.76262697]
 ...
 [ 4.77359915  1.16693991 -0.55865383 ...  1.47461278  1.13016676
  -1.79031443]
 [-0.29752208 -1.00110871 -0.55865383 ...  1.7379296  -0.67704558
  -0.40820477]
 [-0.29752208 -0.08824613  1.74301844 ...  0.87274574 -1.11077654
   0.34447277]]


## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Predicting a new result

In [ ]:

print(classifier.predict(sc.transform(X_test)))

['Enrolled' 'Dropout' 'Graduate' ... 'Enrolled' 'Graduate' 'Graduate']


## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Graduate' 'Graduate']
 ['Dropout' 'Dropout']
 ['Graduate' 'Graduate']
 ...
 ['Dropout' 'Enrolled']
 ['Graduate' 'Graduate']
 ['Graduate' 'Graduate']]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[266  43  44]
 [ 44  71  78]
 [ 18  18 524]]


0.7784810126582279